blueprint:
  name: Tag scan to open door
  description: Open the door and sent notifications when a door is opened.
  source_url: https://github.com/StevusPrimus/homeassistant-scripts/blob/main/blueprints/tag_scan_door_open.yaml
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    tag:
      name: Tag
      selector:
        tag:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

